# Generated by Django 2.2 on 2021-08-31 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_mac', models.CharField(max_length=1000)),
                ('total', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('ordered', models.BooleanField(default=False)),
                ('receipt_no', models.CharField(blank=True, max_length=1000, null=True)),
                ('payment_method', models.CharField(default='Other', max_length=100)),
                ('phone_no', models.CharField(blank=True, max_length=100, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('house', models.ManyToManyField(to='agency.House')),
            ],
        ),
        migrations.CreateModel(
            name='BookedHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_mac', models.CharField(max_length=1000)),
                ('paid', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('finished', models.BooleanField(default=False)),
                ('bookedhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.House')),
            ],
        ),
    ]
