# Generated by Django 2.2 on 2021-08-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_bookedhouse_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_mac',
            field=models.CharField(default='empty', max_length=1000),
        ),
    ]
