# Generated by Django 2.2 on 2021-08-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_auto_20210809_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='house_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
