# Generated by Django 2.2 on 2021-08-09 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
    ]
